### ISSUE TITLE
运行出错：importlib.metadata.PackageNotFoundError: pypinyin

### ISSUE THREAD

**Issue by roachsinai** [mozillazg/python-pinyin#222]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Manjaro Linux
* Python 版本：3.7
* pypinyin 版本：0.40.0

## 问题描述

`importlib.metadata.PackageNotFoundError: pypinyin`错误。

```
hmanx ~ » pyenv activate nn
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(nn) hmanx ~ » pip install pypinyin    
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pypinyin
  Downloading https://mirrors.aliyun.com/pypi/packages/db/50/58b16cb56aeb003246d76ce3648f8e449605d7595e444a9b7c87bd543db8/pypinyin-0.40.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 3.4 MB/s 
Installing collected packages: pypinyin
Successfully installed pypinyin-0.40.0
WARNING: You are using pip version 20.2; however, version 20.3.1 is available.
You should consider upgrading via the '/home/roach/.pyenv/versions/3.7.4/envs/nn/bin/python3.7 -m pip install --upgrade pip' command.
(nn) hmanx ~ » pypinyin 曹坐系桶 -s NORMAL
Traceback (most recent call last):
  File "/usr/bin/pypinyin", line 33, in <module>
    sys.exit(load_entry_point('pypinyin==0.37.0', 'console_scripts', 'pypinyin')())
  File "/usr/bin/pypinyin", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pypinyin
```

## 问题复现步骤

通过系统包管理器安装或者在Python虚拟环境中安装pypinyin只有，执行pypinyin都报了以上的错误。

**Comment by mozillazg** [comment]
看起来似乎是你系统上的多个 Python 版本没有完全隔离或者是当前 shell 的设置导致依赖没有隔离，可以试试下面的方法：

```
# 安装
$ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/python3.7 -m pip install pypinyin

# 命令行工具
$ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/python3.7 -m pypinyin 曹坐系桶 -s NORMAL
# or
$ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/pypinyin 曹坐系桶 -s NORMAL
```

**Comment by roachsinai** [comment]
> 看起来似乎是你系统上的多个 Python 版本没有完全隔离或者是当前 shell 的设置导致依赖没有隔离，可以试试下面的方法：
> 
> ```
> # 安装
> $ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/python3.7 -m pip install pypinyin
> 
> # 命令行工具
> $ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/python3.7 -m pypinyin 曹坐系桶 -s NORMAL
> # or
> $ /home/roach/.pyenv/versions/3.7.4/envs/nn/bin/pypinyin 曹坐系桶 -s NORMAL
> ```

是的这样可以。然后我直接使用发行版包管理器安装的就会报错。我虚拟环境的错误应该是pypinyin执行的还是/usr/bin/pypinyin。

**Comment by roachsinai** [comment]
可能是Manjaro某些地方落后Archlinux的原因吧。

**Comment by roachsinai** [comment]
是Archlinux的包已经基于python3.9了。感谢。
