### ISSUE TITLE
Windows 11 Nuitka 打包后找不到 json 数据文件

### ISSUE THREAD

**Issue by anzhi0708** [mozillazg/python-pinyin#332]
## 运行环境

* 操作系统：Windows 11
* Python 版本：3.11.9
* pypinyin 版本：0.53.0

## 问题描述

使用 [nuitka](https://github.com/Nuitka/Nuitka) 编译器打包脚本为可执行文件后，运行EXE时提示在临时目录下找不到 pinyin_dict.json 数据文件。
查看[官网 Changelog](https://pypinyin.readthedocs.io/zh-cn/master/CHANGELOG.html) 后，发现虽然提及了已经添加对`PyInstaller`的支持（2024-09-15），但没有提到是否支持`Nuitka`
**由于之前使用 0.51.0 时未遇到该问题，尝试把 pypinyin 版本降级为 0.51.0 后问题解决**

## 问题复现步骤

0.53.0 版本使用`python -m nuitka --onefile --standalone`编译为EXE后应该可以复现该问题。推测 0.52.0 可能存在相同的问题，Win11下报错为找不到 AppData 临时文件夹下的 json 数据文件

**Comment by mozillazg** [comment]
@anzhi0708 感谢反馈。可以尝试在编译时增加一个参数 `--include-package-data=pypinyin` 应该可以解决这个问题，比如：

```
python -m nuitka --onefile --standalone --include-package-data=pypinyin main.py
```

参考文档：https://nuitka.net/user-documentation/user-manual.html#package-data-include-package-data-package

我后面调研一下，看看 Nuitka 是否提供了类似 PyInstaller 提供的不需要在打包时新增参数或配置就可以解决这个问题的机制。

**Comment by anzhi0708** [comment]
### 加上`--include-package-data=pypinyin`后，问题解决。`nuitka`的输出也会提示加入了两个JSON
```console
uv run python -m nuitka --standalone --onefile --include-package-data=pypinyin .\hello.py
```
```text
...
Nuitka-Options: Included data file 'pypinyin\phrases_dict.json' due to package
Nuitka-Options: 'pypinyin' package data.
Nuitka-Options: Included data file 'pypinyin\pinyin_dict.json' due to package
Nuitka-Options: 'pypinyin' package data.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a
Nuitka-Postprocessing: while.
...
```
```console
uv tree
Resolved 7 packages in 1ms
pypinyin-test v0.1.0
├── nuitka v2.4.9
│   ├── ordered-set v4.1.0
│   └── zstandard v0.23.0
└── pypinyin v0.53.0
```

### 作为对照，编译了一个不加 flag 的版本
```console
uv run python -m nuitka --standalone --onefile .\hello.py --output-dir=without_flag
.\without_flag\hello.exe
```
```text
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\hello.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pypinyin\__init__.py", line 9, in <module pypinyin>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pypinyin\constants.py", line 11, in <module pypinyin.constants>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pypinyin\pinyin_dict.py", line 22, in <module pypinyin.pinyin_dict>
  File "C:\Users\USER\AppData\Local\Temp\ONEFIL~2\pypinyin\pinyin_dict.py", line 15, in _load_pinyin_dict
  File "codecs.py", line 918, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\AppData\\Local\\Temp\\onefile_22536_133734396401813564\\pypinyin\\pinyin_dict.json'
```
