### ISSUE TITLE
可否支持IronPython库

### ISSUE THREAD

**Issue by LevyLession** [mozillazg/python-pinyin#85]
IronPython库作用是可.Net和Python之间的互相调用,
而IronPython库感觉像是独立的Python环境, 但IronPython与Python2.7却有一些差异
主要原因是IronPython中处理字符串均是unicode, 看以下代码:
```
# IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
# Type "help", "copyright", "credits" or "license" for more information.
import pypinyin
from pypinyin import pinyin
pinyin('成都')
#报出以下错误
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pypinyin\core.py", line 250, in pinyin
#  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pypinyin\core.py", line 32, in seg
#  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pypinyin\core.py", line 34, in seg
#  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pypinyin\utils.py", line 48, in simple_seg
#AssertionError: must be unicode string or [unicode, ...] list

########################################
print unicode   #output <type 'str'>
print str       #output <type 'str'>
# 从上面两行代码可以看出, 在IronPython环境中, unicode与str完全是相同的
print sys.version_info
#output sys.version_info(major=2, minor=7, micro=7, releaselevel='final', serial=0)
print sys.subversion
#output ('IronPython', '', '')
```
从上面可以看出 在IronPython输出的版本是2.7.7.0, 在你compat.py中判定`PY2`变量为`True`, 所以`bytes_type`的结果为`<type str>`
由于在IronPython中输出`unicode`与`str`是都是`str`, 所以在`utils.py`对`hans`判断为`bytes_type`时便会报`must be unicode string or [unicode, ...] list`
希望可以在`compat.py`文件对`PY2`变量加以下判断
```
PY2 = sys.version_info < (3, 0) and sys.subversion[0] != 'IronPython'
```

**Comment by mozillazg** [comment]
@LevyLession 麻烦试一下，看看 `pinyin(u'成都')` 是否也报错？

**Comment by LevyLession** [comment]
@mozillazg  报错是必然的, 是因为pypinyin\utils.py", line 48, in simple_seg这个函数报的错`must be unicode string or [unicode, ...] list`
原因就是因为在IronPython运行runtime内, 读取到的Version是2.7.7  而我装的python是2.7.13  这说明了IronPython并不是使用的Python的相关版本之类的信息, compat.py文件的`PY2 = sys.version_info < (3, 0)`这行代码检测到是2.7.7版本,便使得
```
text_type = unicode
bytes_type = str
```
但有IronPython有个坑爹的地方
IronPython运行环境执行如下:
```
C:\Program Files (x86)\IronPython 2.7>ipy
IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> unicode
<type 'str'>
>>> str
<type 'str'>
>>> isinstance(unicode(u'成都'), str)
True
```
上面的代码是IronPython在命令行中运行的结果,  也就是说, 在IronPython环境下, unicode就是str  str也是str
所以在utils文件的simple_seg函数以下代码**绝对会报错**
```
assert not isinstance(hans, bytes_type), \
    'must be unicode string or [unicode, ...] list'
```
因为bytes_type在上面PY2判断时设置了为str, 这就悲剧了, 因为isinstance(<type 'unicode'>, str) 是True

**因为IronPython要和C#交互, 所以在IronPython中的str就是unicode, 所以`unicode`恒等于`str`**
---
然后我在你的代码上更改了`compat.py`文件的`PY2`变量的判断, 就可以正常运行了:
```
PY2 = sys.version_info < (3, 0) and sys.subversion[0]!='IronPython' # and 后面是我添加的,只加了这个判断
if not PY2:
    text_type = str
    bytes_type = bytes
else:
    text_type = unicode           # noqa
    bytes_type = str
```

**Comment by LevyLession** [comment]
@mozillazg 我也实在没办法了, 之前我这要求拼音首字母大写, 看了下pypinyin的代码, 发现可以register 转换方法, 我便copy了一份`style/others.py`文件并做了调整, 然后自己register一下, 就可以使用了
---
但这个实在没办法, 我怎么也没办法把`bytes_type`的值更改为`bytes`

**Comment by mozillazg** [comment]
@LevyLession 麻烦帮忙测试一下 https://github.com/mozillazg/python-pinyin/pull/86 的改动是否解决了你的问题。

**Comment by LevyLession** [comment]
@mozillazg 
谢谢, 已经可以使用
```
C:\Program Files (x86)\IronPython 2.7>ipy
IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypinyin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pypinyin

>>> import pypinyin
>>> from pypinyin import pinyin
>>> pinyin('成都')
Building prefix dict from the default dictionary ...
Loading model from cache c:\users\ll6y\appdata\local\temp\jieba.cache
Loading model cost 1.098 seconds.
Prefix dict has been built succesfully.
[[u'ch\xe9ng'], [u'd\u016b']]
>>> pinyin(u'成都')
[[u'ch\xe9ng'], [u'd\u016b']]
```
反手就是36个赞~

**Comment by mozillazg** [comment]
@LevyLession 刚发布了一个新版本，麻烦帮忙测试一下最新版的 pypinyin 是否解决了这个问题。谢谢！

**Comment by LevyLession** [comment]
@mozillazg 
master版本已经可用,  谢谢~

**Comment by mozillazg** [comment]
@LevyLession 不客气。感谢帮忙测试。
